{% set name = "pandas-profiling" %}
{% set version = "2.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: abe4cb7b1cf9533dd5e3d16bea6c99c062df4441219abd386f881eec1480351b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - scipy >=1.4.1
    - requests >=2.23.0
    - missingno >=0.4.2
    - pandas >=0.25.3
    - matplotlib-base >=3.2.0
    - jinja2 >=2.11.1
    - htmlmin >=0.1.12
    - phik >=0.9.10
    - confuse >=1.0.0
    - astropy >=4.0
    - visions >=0.4.1
    - numpy >=1.16.0
    - statsmodels >=0.11.1
    - tangled-up-in-unicode >=0.0.4
    - tqdm >=4.43.0
    - ipywidgets >=7.5.1

test:
  imports:
    - pandas_profiling

about:
  home: http://github.com/pandas-profiling/pandas-profiling
  license: MIT
  license_file: LICENSE
  summary: Generate profile report for pandas DataFrame
  dev_url: http://github.com/pandas-profiling/pandas-profiling
  doc_url: https://pandas-profiling.github.io/pandas-profiling/docs/

extra:
  recipe-maintainers:
    - sbrugman
    - proinsias
    - philip-khor
