travis:
  secure:
    BINSTAR_TOKEN: Lv5xSndhUcHlSh4rsn7+MYWVaIUw1jzItYbXcawKs47BY30kTJLJoam15ahsNUVFE+97XZldS4Q2TcywLmWz1g7YQQoJmqntvFqjWurEDMGN9YFYUQoGhJttay+CszMQdB6Cxa4nPDyQpBwVpdUH8Gl5VWSQhKpaKfMLFoY8f1WrArV12+7GmzAg+8LfI0wS9U6Gh84dW9Fq7fRmn/bGDIO5YrGZtdlS26A9r65s4GQQ1b1PgSYBrVieVjTwYAZP1+wBKpLnLdt0dXAhCdXgczahA2rk5vIfOuBk0FpqYOao1rmofctCV3YYk/ZwyfitDQHw6LZhPmeqfvUaSYGAoujM1eLY7s8NXG1YxJDu/KMZzJfwP39sJs5nFzx6V+aujJNO+Mgi2wOZx6AdpXhL0cNZmHHuLHYFdB1THOlQAcj1gMeQSpQoY9+HWiLJFspNYzz7zXldPl0VWKkJhfmVje3E/qyHoEbtTbcDVKwrzkxhv/0x32IxmWF9Szq0W+StVy3DMuBxi8bDZXetE8cLqp2DNSCnZ5mETvtBwuHrXfZxwc15MeN/isgcF4K/ENXP29ifTfOHQfjAAbVCqgeQn7i2TcDkS+WAGXh3HmZlN7cYoGm/tMSok1AFXDUdNWDm7G6pb3n05IkuHVawV9pH1ps6T1jvKbeYZ8JfwZ8yDpI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
bot:
  automerge: true
